### ISSUE TITLE
User 모델에 대한 CRUD 생성하기

### ISSUE THREAD

**Issue by 10000001a** [today-route/today-route-server#1]
## 🗒 Tasks

- [x] user 회원가입 API 구현
- [x] user 로그인 API 구현
- [x] user 로그아웃 API 구현
- [x] user 정보 추가 / 수정 API 구현
- [ ] user 탈퇴 API 구현
- [ ] test 코드 작성
